[slave]
slave-1 ansible_host=168.144.87.145 ansible_user=root ansible_python_interpreter=/usr/bin/python3 ansible_ssh_private_key_file=/var/lib/semaphore/.ssh/id_ed25519 ansible_ssh_common_args='-o StrictHostKeyChecking=yes -o UserKnownHostsFile=/var/lib/semaphore/.ssh/known_hosts'
